[package]
name = "common"
version = "0.1.0"
edition = "2024"

[lib]
name = "common"
crate-type = ["staticlib", "rlib"]

[build-dependencies]
cbindgen = "0.28"

[dependencies]
libc = "0.2"