[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
actix-cors = "0.7.1"

log = "0.4.27"
env_logger = "0.11.8"
dotenvy = "0.15.7"
diesel = { version = "2.2.9", features = ["postgres"] }

lazy_static = "1.5.0"
