services:
  database-server:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - database-data:/var/lib/postgresql/data
    env_file:
      - ../core/server/app/.env

  browserless-chrome:
    image: browserless/chrome:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DEFAULT_STEALTH=true
      - CONNECTION_TIMEOUT=120000
      - CHROME_REFRESH_TIME=3600000
      - DEFAULT_HEADLESS=new
      - DEFAULT_LAUNCH_ARGS=["--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","--window-size=1920,1080","--disable-web-security","--disable-features=VizDisplayCompositor","--disable-blink-features=AutomationControlled","--disable-infobars","--no-sandbox","--disable-setuid-sandbox","--disable-dev-shm-usage","--disable-accelerated-2d-canvas","--disable-gpu","--lang=en-US,en"]
      - DEFAULT_IGNORE_HTTPS_ERRORS=true
      - DEFAULT_BLOCK_ADS=true
      - KEEP_ALIVE=true

  development:
    build:
      context: ..
      dockerfile: Dockerfile.dev
    depends_on:
      - database-server
      - browserless-chrome
    command: sleep infinity
    volumes:
      - cargo-cache:/usr/local/cargo
      - ..:/workspace:cached

volumes:
  database-data:
  cargo-cache:
