[package]
name = "auth"
version = "0.1.0"
edition = "2024"

[dependencies]
rust-argon2 = "2.1.0"
rand = "0.9.1"
jsonwebtoken = "9.2.0"
anyhow = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
